# Generated by Django 5.2.1 on 2025-09-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenities',
            new_name='Amenity',
        ),
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(default='my business', max_length=100),
        ),
    ]
