# Generated by Django 5.2.1 on 2025-09-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_amenities_amenity_hotelvendor_business_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelimages',
            options={'ordering': ['-is_primary', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='hotelimages',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotelimages',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelimages',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelimages',
            name='image',
            field=models.ImageField(upload_to='hotel_images/'),
        ),
    ]
